#!/bin/sh
#bsd-cloudinit workaround

#usage
#echo ./root/bsd-cloudinit.sh >> /etc/rc.local
#chmod u+x /root/bsd-cloudinit.sh

# pkg install ca_root_nss
# pkg install jq
# pkg install bash

PATH='/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin'
LOADER_CONF='/boot/loader.conf'

echo_bsdinit_stamp() {
	echo '# Generated by bsd-cloudinit-installer '`date +'%Y/%m/%d %T'`
}

export PATH=$PATH

#disk_resize
gpart recover vtbd0
sysctl kern.geom.debugflags=16
gpart resize -i 2 vtbd0
growfs -y vtbd0p2

#set passwordless sudo
#echo 'freebsd ALL=(ALL) NOPASSWD: ALL' > /usr/local/etc/sudoers.d/10-cloudinit

#set_key
#fetch http://169.254.169.254/openstack/latest/meta_data.json -q -o - | jq -r '.keys[] |.data' > /home/freebsd/.ssh/authorized_keys

#set_hostname
fqdn=$(fetch http://169.254.169.254/openstack/latest/meta_data.json -q -o - | jq ".hostname" | sed "s/.novalocal//g")

sed -i "" "s/hostname.*/hostname=$fqdn/g" /etc/rc.conf
hostname $(echo $fqdn | tr -d '"')

#get userdata
fetch http://169.254.169.254/openstack/latest/user_data -q -o - | sh

#set root passwd
#pw mod user root -w random > /dev/null
#echo $pass | pw mod user root -h 0

# Output to OpenStack console log
echo_bsdinit_stamp >> $LOADER_CONF
echo 'console="vidconsole,comconsole"' >> $LOADER_CONF
# Bootloader menu delay
echo 'autoboot_delay="1"' >> $LOADER_CONF

sed -i "" "s/.*bsd-cloudinit.sh//g" /etc/rc.local
set history = 0
rm -f /root/bsd-cloudinit.sh
#make clean
# set history = 0
# ssh-keygen -A
#
# #do Cheshire Cat
# sed -i "" "s/.*bsd-cloudinit//g" /etc/rc.local
# rm -f /root/bsd-cloudinit
